# Generated by Django 3.2.6 on 2025-03-13 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioRecomendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.docente')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.horario')),
            ],
            options={
                'unique_together': {('docente', 'asignatura', 'horario')},
            },
        ),
    ]
