# Generated by Django 3.2.6 on 2025-03-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_domicilio/'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='titulo',
            field=models.FileField(blank=True, null=True, upload_to='titulos/'),
        ),
    ]
