# Generated by Django 3.2.6 on 2025-03-20 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_asignacionmateria'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionmateria',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.carrera'),
            preserve_default=False,
        ),
    ]
