# Generated by Django 3.2.6 on 2025-03-26 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_asignacionmateria_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('hora_inicio', models.CharField(choices=[('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], max_length=5)),
                ('hora_fin', models.CharField(choices=[('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], max_length=5)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='home.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='asignacionmateria',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='asignacionmateria',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='asignacionmateria',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='asignacionmateria',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='asignacionmateria',
            name='horario',
        ),
        migrations.AlterUniqueTogether(
            name='horariorecomendado',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='horariorecomendado',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='horariorecomendado',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='horariorecomendado',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='reportecargaacademica',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='carreras',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='codigo',
        ),
        migrations.AddField(
            model_name='administrador',
            name='apellido_materno',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='apellido_paterno',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.carrera'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='clave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='administrador',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='telefono',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignatura',
            name='clave',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignatura',
            name='matricula',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrera',
            name='clave',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrera',
            name='horas_semanales',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.docente'),
        ),
        migrations.AddField(
            model_name='horario',
            name='hora',
            field=models.CharField(choices=[('07:00 - 08:30', '07:00 - 08:30'), ('08:30 - 10:00', '08:30 - 10:00'), ('10:00 - 11:30', '10:00 - 11:30'), ('11:30 - 13:00', '11:30 - 13:00'), ('13:00 - 14:30', '13:00 - 14:30'), ('14:30 - 16:00', '14:30 - 16:00'), ('16:00 - 17:30', '16:00 - 17:30'), ('17:30 - 19:00', '17:30 - 19:00'), ('19:00 - 20:30', '19:00 - 20:30')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.asignatura'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.carrera'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('dia', 'hora', 'docente')},
        ),
        migrations.DeleteModel(
            name='Asignacion',
        ),
        migrations.DeleteModel(
            name='AsignacionMateria',
        ),
        migrations.DeleteModel(
            name='HorarioRecomendado',
        ),
        migrations.DeleteModel(
            name='ReporteCargaAcademica',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.asignatura'),
        ),
        migrations.RemoveField(
            model_name='horario',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.periodo'),
        ),
    ]
