# Generated by Django 3.2.6 on 2025-04-03 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
