# Generated by Django 3.2.6 on 2025-04-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20250402_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='Grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.grupo'),
        ),
    ]
