# Generated by Django 3.2.6 on 2025-04-03 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_asignatura_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='visible_para_todos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docente',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.carrera'),
        ),
    ]
