# Generated by Django 3.2.6 on 2025-04-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20250403_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='carrera',
        ),
        migrations.AddField(
            model_name='administrador',
            name='carreras',
            field=models.ManyToManyField(blank=True, to='home.Carrera'),
        ),
    ]
