# Generated by Django 3.2.6 on 2025-04-03 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_disponibilidaddocente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilidaddocente',
            old_name='materia',
            new_name='asignatura',
        ),
        migrations.AddField(
            model_name='disponibilidaddocente',
            name='horarios',
            field=models.ManyToManyField(to='home.HorarioAsignatura'),
        ),
        migrations.AddField(
            model_name='disponibilidaddocente',
            name='horas_semanales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disponibilidaddocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='home.docente'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidaddocente',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
        migrations.RemoveField(
            model_name='disponibilidaddocente',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='disponibilidaddocente',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='disponibilidaddocente',
            name='hora_inicio',
        ),
    ]
