# Generated by Django 3.2.6 on 2025-04-03 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20250403_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidaddocente',
            name='horas_semanales',
        ),
        migrations.CreateModel(
            name='HorarioDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_semanales', models.IntegerField(default=0)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_docente', to='home.docente')),
                ('horarios', models.ManyToManyField(to='home.HorarioAsignatura')),
            ],
        ),
    ]
